# Code to create sub folders

dir.create("R")
dir.create("R/AirConcCalculations")
dir.create("R/AirConcCalculations/ACE")
dir.create("R/AirConcCalculations/AESOP")
dir.create("R/AirConcCalculations/AESOP/PUFPASMOdel")
dir.create("R/DataAcquisitionNOAA")
dir.create("R/Extra")
dir.create("R/Extra/AirChicagoData")
dir.create("R/Extra/Flux")
dir.create("R/Extra/Soil")
dir.create("R/Extra/SoilAirExchange")

dir.create("Data")
dir.create("Data/Air")
dir.create("Data/Air/EastChicago")
dir.create("Data/Air/EastChicago/ACE")
dir.create("Data/Air/EastChicago/AESOP")
dir.create("Data/Air/EastChicago/AESOP/PUFPASModel")
dir.create("Data/Extra")
dir.create("Data/Extra/Chicago")
dir.create("Data/Extra/Flux")
dir.create("Data/Extra/Soil")
dir.create("Data/Meteorology")
dir.create("Data/PCProperties")
dir.create("Data/RemediationProject")

dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/Air")
dir.create("Output/Data/Soil")
dir.create("Output/PUFPASModel")
dir.create("Output/PUFPASModel/Meteo")
dir.create("Output/PUFPASModel/Meteo/isd_light")
dir.create("Output/PUFPASModel/Meteo/MERRA")
dir.create("Output/PUFPASModel/Vef")
dir.create("Output/PUFPASModel/Vef/isd_light")
dir.create("Output/PUFPASModel/Vef/MERRA")
dir.create("Output/Plots")
dir.create("Output/Plots/Concentrations")
dir.create("Output/Plots/PartialPressure")

