# Code to create sub folders

dir.create("R")
dir.create("R/Analysis")
dir.create("R/ConcentrationCalculations")
dir.create("R/PUFPASModel")
dir.create("R/Flux")
dir.create("Data")
dir.create("Data/PUFPASModel")
dir.create("Data/Flux")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/csv")
dir.create("Output/Data/excel")
dir.create("Output/PUFPASModel")
dir.create("Output/PUFPASModel/Meteo")
dir.create("Output/PUFPASModel/Meteo/isd_light")
dir.create("Output/PUFPASModel/Meteo/MERRA")
dir.create("Output/PUFPASModel/Vef")
dir.create("Output/PUFPASModel/Vef/isd_light")
dir.create("Output/PUFPASModel/Vef/MERRA")
dir.create("Output/Plots")
dir.create("Output/Plots/Concentrations")


