# Code to create sub folders

dir.create("R")
dir.create("R/RemediationActivities")
dir.create("R/AirConcCalculations")
dir.create("R/AirConcCalculations/ACE")
dir.create("R/AirConcCalculations/AESOP")
dir.create("R/AirConcCalculations/AESOP/PUFPASMOdel")
dir.create("R/DataAcquisitionNOAA")
dir.create("R/DataAcquisitionUSGS")
dir.create("R/DataProcessing")
dir.create("R/Extra")
dir.create("R/Extra/AirChicagoData")
dir.create("R/Extra/Flux")
dir.create("R/Extra/Soil")
dir.create("R/Extra/SoilAirExchange")
dir.create("R/ParPreCalculations")
dir.create("R/StatisticalAnalysis")

dir.create("Data")
dir.create("Data/ACE")
dir.create("Data/Air")
dir.create("Data/Air/EastChicago")
dir.create("Data/Air/EastChicago/ACE")
dir.create("Data/Air/EastChicago/AESOP")
dir.create("Data/Air/EastChicago/AESOP/PUFPASModel")
dir.create("Data/Extra")
dir.create("Data/Extra/Chicago")
dir.create("Data/Extra/Flux")
dir.create("Data/Extra/Soil")
dir.create("Data/FinalDataset")
dir.create("Data/Mike")
dir.create("Data/Meteorology")
dir.create("Data/PCProperties")
dir.create("Data/RemediationActivities")
dir.create("Data/USGS")

dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/Air")
dir.create("Output/Data/Air/StatisticalAnalysis")
dir.create("Output/Data/Air/StatisticalAnalysis/PCB8")
dir.create("Output/Data/Air/StatisticalAnalysis/PCB15")
dir.create("Output/Data/Air/StatisticalAnalysis/PCB18.30")
dir.create("Output/Data/Air/StatisticalAnalysis/PCB20.28")
dir.create("Output/Data/Air/StatisticalAnalysis/PCB31")
dir.create("Output/Data/CorrelationAnalysis")
dir.create("Output/Data/Soil")
dir.create("Output/PUFPASModel")
dir.create("Output/PUFPASModel/Meteo")
dir.create("Output/PUFPASModel/Meteo/isd_light")
dir.create("Output/PUFPASModel/Meteo/MERRA")
dir.create("Output/PUFPASModel/Vef")
dir.create("Output/PUFPASModel/Vef/isd_light")
dir.create("Output/PUFPASModel/Vef/MERRA")
dir.create("Output/Plots")
dir.create("Output/Plots/Concentrations")
dir.create("Output/Plots/CorrelationAnalysis")
dir.create("Output/Plots/Extra")
dir.create("Output/Plots/MeteoComparison")
dir.create("Output/Plots/PartialPressure")


